variable function_name {}
variable role {}
variable runtime {}
variable handler {}
variable timeout {}
variable lambda_script_name {}
variable "lambda_sns_topic_arn" {}
variable "lambda_ddb_table_name" {}
variable "lambda_audiostorage_bucket_name" {}
